name: Scrape Universities CI

on:
  push:
    branches:
      - main

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Scrape and save universities
      run: |
        python scraper.py

    - name: upload universities
      uses: actions/upload-artifact@v2
      with:
        name: universities
        path: universities.json
